AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: This function creates posts in DynamoDB
Resources:
  PostReaderNewPosts:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: new_post.lambda_handler
      Runtime: python2.7
      CodeUri: .
      Description: This function creates posts in DynamoDB
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::606791903163:role/LambdaRuleForPolly'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /
            Method: POST
      Environment:
        Variables:
          DB_TABLE_NAME: posts
          SNS_TOPIC: 'arn:aws:sns:us-east-1:606791903163:new_posts'
