AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Converts my text to audio files and saves to s3
Resources:
  PostReaderConvertToAudio:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python2.7
      CodeUri: .
      Description: Converts my text to audio files and saves to s3
      MemorySize: 128
      Timeout: 300
      Role: 'arn:aws:iam::606791903163:role/LambdaRuleForPolly'
      Events:
        SNS1:
          Type: SNS
          Properties:
            Topic:
              Ref: SNSTopic1
      Environment:
        Variables:
          BUCKET_NAME: polly-mp3s2018b
          DB_TABLE_NAME: posts
  SNSTopic1:
    Type: 'AWS::SNS::Topic'
